---
name: gatorgrader-samplelab
break: true
fastfail: false
indent: 4
version: v0.2.0
executables: cat, bash
---
src/main:
    java:
        samplelab/SampleLabMain.java:
            --exists
            --single 1 --language Java
            --multi 3 --language Java
            --fragment "println(" --count 2
            --fragment "new DataClass(" --count 1
            --regex "new\s+\S+?\(.*?\)" --count 2 --exact
        samplelab/DataClass.java:
            --exists
            --multi 1 --language Java
            --single 1 --language Java
            --fragment "int " --count 1
writing/reflection.md:
    mdl
    cat
    --paragraphs 2
    --words 6
--commits 18
